#!/bin/env python

import katareversi

def test_read_board():
    data = '''
........
........
........
...BW...
...WB...
........
........
........
B'''
    board,turn = katareversi.read_board(data[1:])
    assert turn == 'B', 'Wrong turn: '+turn
    assert board.row(3).col(3) == 'B'
    assert board.row(3).col(4) == 'W'
    assert board.row(4).col(3) == 'W'
    assert board.row(4).col(4) == 'B'
    assert board.row(4).col(5) == '.'

def test_next_square():
    row, col = katareversi.next_square(1, 1, 'N')
    assert row == 0
    assert col == 1
    row, col = katareversi.next_square(1, 1, 'SW')
    assert row == 2
    assert col == 0

def test_check_direction():
    data = '''
........
........
........
...BW...
...WB...
........
........
........
B'''
    board,turn = katareversi.read_board(data[1:])
    assert katareversi.check_direction(board, 2, 4, 'B', True)

def test_check_board_position():
    return
    data = '''
........
........
........
...BW...
...WB...
........
........
........
B'''
    board,turn = katareversi.read_board(data[1:])
    assert katareversi.check_board_position(board, row=2, col=4, turn='B') == True
    assert katareversi.check_board_position(board, row=2, col=4, turn='W') == False

def test_check_entire_board():
    pass

def test_output():
    pass
